### ISSUE TITLE
Questions: are the analog interface schematics available, too?

### ISSUE THREAD

**Issue by sixtyfive** [hansgelke/retro_v3#1]
(Want to find out if the phones might also work on an old Fritz!Box's TAE port...)

**Comment by hansgelke** [comment]
The external line was tested on a Fritz box TAE line

**Comment by hansgelke** [comment]
After I checked the schematics, I will add them

**Comment by sixtyfive** [comment]
Thank you for the quick respone! It's not quite what I meant, but I guess I'll understand better once the schematics are online :)
